# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mobile_app_distribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mobile_app_distribution', '0005_auto_20160118_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='app',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AlterField(
            model_name='iosapp',
            name='display_image',
            field=models.ImageField(blank=True, default='', help_text='57x57 PNG', upload_to=django_mobile_app_distribution.models.normalize_image_filename, verbose_name='display image'),
        ),
        migrations.AlterField(
            model_name='iosapp',
            name='full_size_image',
            field=models.ImageField(blank=True, default='', help_text='512x512 PNG', upload_to=django_mobile_app_distribution.models.normalize_image_filename, verbose_name='full size image'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('ja', '日本語')], default='en', max_length=20, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
